### ISSUE TITLE
Error when trying to train YOLOv8-PA-STP3-s.yaml with ultralytics

### ISSUE THREAD

**Issue by paranoiks** [bgno1/modular_yolov8_sds#1]
I am following this repo, trying to train one of the example models (**YOLOv8-PA-STP3-s.yaml**)

I have compied the **GAM.py** and **SwinTransformer.py** files to the **nn/modules** and I have edited **nn/tasks.py (line 696)** to include both the values in the **if m in {...** block

I then run this command to train the model:

```
yolo task=detect mode=train model=YOLOv8-PA-STP3-s.yaml data=coco8.yaml epochs=10
```

But I get the following error:

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\source\personal\ultralytics\.venv\Scripts\yolo.exe\__main__.py", line 7, in <module>
  File "c:\source\personal\ultralytics\.venv\Lib\site-packages\ultralytics\cfg\__init__.py", line 943, in entrypoint
    model = YOLO(model, task=task)
            ^^^^^^^^^^^^^^^^^^^^^^
  File "c:\source\personal\ultralytics\.venv\Lib\site-packages\ultralytics\models\yolo\model.py", line 23, in __init__
    super().__init__(model=model, task=task, verbose=verbose)
  File "c:\source\personal\ultralytics\.venv\Lib\site-packages\ultralytics\engine\model.py", line 144, in __init__
    self._new(model, task=task, verbose=verbose)
  File "c:\source\personal\ultralytics\.venv\Lib\site-packages\ultralytics\engine\model.py", line 255, in _new
    self.model = (model or self._smart_load("model"))(cfg_dict, verbose=verbose and RANK == -1)  # build model
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\source\personal\ultralytics\.venv\Lib\site-packages\ultralytics\nn\tasks.py", line 322, in __init__
    self.model, self.save = parse_model(deepcopy(self.yaml), ch=ch, verbose=verbose)  # model, savelist
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\source\personal\ultralytics\.venv\Lib\site-packages\ultralytics\nn\tasks.py", line 1070, in parse_model
    m_ = nn.Sequential(*(m(*args) for _ in range(n))) if n > 1 else m(*args)  # module
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\source\personal\ultralytics\.venv\Lib\site-packages\ultralytics\nn\tasks.py", line 1070, in <genexpr>
    m_ = nn.Sequential(*(m(*args) for _ in range(n))) if n > 1 else m(*args)  # module
                         ^^^^^^^^
TypeError: 'module' object is not callable
```

Adding a **print(m)** to line 1069 yields the following just before the error:
```
<module 'ultralytics.nn.modules.SwinTransformer' from 'c:\\source\\personal\\ultralytics\\.venv\\Lib\\site-packages\\ultralytics\\nn\\modules\\SwinTransformer.py'>
```

**Comment by bgno1** [comment]
Hello, the issue seems to be caused by the import statement. Please ensure that SwinTransformer is imported correctly, for example:
`from ultralytics.nn.modules.SwinTransformer import SwinTransformer`
If the issue persists, feel free to comment again.

**Comment by paranoiks** [comment]
This worked thanks a lot! I am now training on the full SeaDroneSee dataset, we'll see how it goes. I also noticed this repo for your unpublished paper: https://github.com/bgno1/sds_yolo11

Would you recommend I use the configs in there? Are they better? I'm completely new to this and don't even know what an ablation study is, is that the main config for the model you used for the study?

**Comment by bgno1** [comment]
> This worked thanks a lot! I am now training on the full SeaDroneSee dataset, we'll see how it goes. I also noticed this repo for your unpublished paper: https://github.com/bgno1/sds_yolo11
> 
> Would you recommend I use the configs in there? Are they better? I'm completely new to this and don't even know what an ablation study is, is that the main config for the model you used for the study?

Yes, I recommend trying the latest YOLO11 directly.
At the time this repository was built, YOLO11 hadn't been released yet. The optimized YOLO11 typically achieves higher accuracy with a more lightweight computational cost.

**Comment by paranoiks** [comment]
I will go for YOLO11 then. Which config would you recommend I go for? Since the paper is unpublished I have no idea what the differences might be. My goal is to train a model on the SeaDronesSee dataset and then run it on the smallest (compute-wise) possible chip
